name: GetChurches
on: [workflow_dispatch]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch
        run: |
          curl -d 'data=[out:json];area["name"="Russia"]->.a;(node["amenity"="place_of_worship"](area.a););out;' https://overpass-api.de > base.json
      - uses: actions/upload-artifact@v4
        with:
          name: my-base
          path: base.json
