name: Collect Churches
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Script
        run: |
          pip install requests
          python crawler/collect_data.py
      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: church-base
          path: Russia_churches.json
