name: Global Church Sync
on: [workflow_dispatch]
jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: pip install requests
      - name: Run Crawler
        run: python crawler/collect_data.py
      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: church-database
          path: "**/*.json" # Робот обыщет ВСЕ папки
